; This file was auto-generated by drush_make
core = 6.x

api = 2


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[pressflow][download][type] = "get"
projects[pressflow][download][url] = "http://files.pressflow.org/pressflow-6-current.tar.gz"
projects[pressflow][type] = "core"


; Profiles
projects[openatrium][type] = "profile"


; Themes
projects[dlr_oa][download][type] = "git"
projects[dlr_oa][download][url] = "git@redmine.wi1projects.com:dlr.git"
projects[dlr_oa][type] = "theme"
projects[dlr_oa][subdir] = "/sites/all/themes"


; Features
; a. non-contrib
projects[atrium_folders][download][type] = "git"
projects[atrium_folders][download][url] = "git://github.com/nuvoleweb/atrium_folders.git"
projects[atrium_folders][type] = "theme"
projects[atrium_folders][subdir] = "/sites/all/features"

  projects[dragndrop_upload][subdir] ="contrib"


; a. custom
; a.1 general
projects[wi1init][download][type] = "git"
projects[wi1init][download][url] = "git@redmine.wi1projects.com:init.git"
projects[wi1init][type] = "theme"
projects[wi1init][subdir] = "/sites/all/features"


; a.2 specific
projects[dlr_groups][download][type] = "git"
projects[dlr_groups][download][url] = "git@redmine.wi1projects.com:dlr/dlr-groups.git"
projects[dlr_groups][type] = "theme"
projects[dlr_groups][subdir] = "/sites/all/features"

