; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.22"

; Profiles
projects[openatrium][type] = "profile"
projects[openatrium][download][type] = get 
projects[openatrium][download][url] = http://openatrium.com/sites/openatrium.com/files/atrium_releases/atrium-1-2.zip

; Modules
projects[admin][subdir] = "profiles/openatrium/modules/contrib/admin"
projects[admin][version] = "2.0"

projects[adminrole][version] = "1.3"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[atrium_folders][download][type] = "git"
projects[atrium_folders][download][url] = "git://github.com/nuvoleweb/atrium_folders.git"
projects[atrium_folders][type] = "module"
projects[atrium_folders][version] = "1.0-dev"

projects[deploy][version] = "1.0-alpha2"

projects[services][version] = "2.x-dev"

projects[context_og][version] = "3.0"

projects[devel][version] = "1.26"

projects[domain][version] = "2.13"

projects[filefield][version] = "3.10"

projects[imagefield][version] = "3.10"

; Themes

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[dlr_oa][download][type] = "git"
projects[dlr_oa][download][url] = "git@redmine.wi1projects.com:dlr.git"
projects[dlr_oa][type] = "theme"

